# Generated by Django 5.1.1 on 2024-10-18 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_homework'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name': 'homeworks', 'verbose_name_plural': 'homeworks'},
        ),
    ]
